### ISSUE TITLE
"Tenancies" organisation on OTC

### ISSUE THREAD

**Issue by cgizzi** [SixSq/hn-prototype-platform#11]
Define how to manage users on OTC side. There is an action for JDM to provide information on this by 28 April

**Comment by cgizzi** [comment]
Bert, please check with Jurry and you/him report to @loomis

**Comment by eeckstei** [comment]
Jurry sent a Excel to Buyers Group how they plan how to group the users and the institutes 2 days ago.
We will wait until we get Feedback from BG.

**Comment by cgizzi** [comment]
Any update on this?

**Comment by eeckstei** [comment]
Jurry remembered Buyers Group in todays call to fill the Excel.

**Comment by mebster** [comment]
@eeckstei @zhenggenqiang when can we expect to have the organisations and accounts created?

**Comment by cgizzi** [comment]
@eeckstei @zhenggenqiang I have sent an email to Jurry. Please get in touch with him as soon as possible to have the acoounts created and the credentials sent out.

**Comment by eeckstei** [comment]
@cgizzi: One Tenant for RHEA Group Intern is already created. You can give me a list of the guys who should be admins there (eMail, Name and Mobile Phone (MP if possible). In parallel we plan to create 9 tenants for Buyers Group asap.

**Comment by cgizzi** [comment]
@eeckstei here it is rhea-hn@rheagroup.com, the "guys": Claudio Gizzi and Sakis Kotisis, the mail alias points to our personal mails, Phone numbers (respectively): : +32 (0)10 48 72 79 and +32 (0)10 48 72 86

**Comment by eeckstei** [comment]
@cgizzi: User in OTC enviroment OTC-EU-DE-00000000001000018694 for Claudio Gizzi, Sakis Kotisis and @zhenggenqiang created. You should got a separate Mail for first Login in OTC RHEA Group Tenant.

**Comment by cgizzi** [comment]
@eeckstei thx. I have requested an additional one for SixSq (also fo internal testing), please ask @mebster (meb@sixsq.com) for details (phone). Once done we can close this task (BG accounts have been also set up)

**Comment by eeckstei** [comment]
@cgizzi Please sent me a note when Tenant for SixSq is created.

**Comment by mebster** [comment]
We need to understand how SixSq can manage these accounts on behalf of the buyers, such that we can create the corresponding entries in the Nuvla accounts, including API keys for both OTC and Exoscale.

**Comment by eeckstei** [comment]
@cgizzi You can add additional users and also SixSQ guys to OTC-EU-DE-00000000001000018694. For buyers Group tenants you are in contact with Jurry. Jurry will provide this when all is clarified.

**Comment by mebster** [comment]
I can confirm that I have access to the OTC account.  Thanks.

For the buyers accounts, please make sure you use the specification @schaubl provided.

**Comment by eeckstei** [comment]
@mebster can you send me a link to the specification.

**Comment by mebster** [comment]
Here's a copy of the original email:

Hi Jurry,

The configuration we would like to have is the following:
- 1 user and 1 tenant per buyer
- 1 SixSq account with access to all tenant (and if possible admin access to the other users)

If the SixSq account can manage (mainly retrieving their API credential) the other users you can create these users with their own email address.
However if it’s not possible please create these users with the email addresses below so that we can manage these users properly.

Please find below the list of users to create for HNSciCloud:

name  | email
--------------------------------------------
CERN   customer_hnscicloud+cern@sixsq.com
CNRS   customer_hnscicloud+cnrs@sixsq.com
DESY   customer_hnscicloud+desy@sixsq.com
EMBL   customer_hnscicloud+embl@sixsq.com
ESRF   customer_hnscicloud+esrf@sixsq.com
IFAE   customer_hnscicloud+ifae@sixsq.com
INFN   customer_hnscicloud+infn@sixsq.com
STFC   customer_hnscicloud+stfc@sixsq.com
KIT     customer_hnscicloud+kit@sixsq.com
RHEA   customer_hnscicloud+rhea@sixsq.com
SixSq   customer_hnscicloud+sixsq@sixsq.com


The email for the account with access to all tenant (and all users above if possible) is:
customer_hnscicloud@sixsq.com

Please return us the above list completed with API credentials (username, API key, tenant name, domain) of each users so that we can configure these accounts on Nuvla.

Regards,
Lionel (SixSq)

**Comment by mebster** [comment]
@eeckstei is that what you were looking for?

**Comment by eeckstei** [comment]
Yes - for this I was looking for.
For RHEA and SixSq you can manage it by yourself in Tenant 1000018694.
For Buyers Group tenants you have to request it from the Responsible Person for the Tenant of BG when them get their tenants, because per Default only one of the BG is admin (and no one of TSI).

**Comment by mebster** [comment]
@eeckstei we need to manage these accounts on behalf of the users.  Could you create these accounts as Lionel's request?  From there, we will be able to create more user accounts for the different buyers.

**Comment by eeckstei** [comment]
@mebster : For BG Tenants I have no Access and therefore I can't create such an account. You have to request BG Responsible to create such an Account when BG-Tenant is created.
For Tenant OTC-EU-DE-00000000001000018694 I can create an User for customer_hnscicloud@sixsq.com (Username: customer_hnscicloud) with only API Access (Access Key) for Management via API only.
Or do you want this user as "normal user", but then the Access Keys (for API) must be created by someone who has Access to eMail customer_hnscicloud@sixsq.com.

**Comment by mebster** [comment]
@eeckstei I am admin on OTC-EU-DE-00000000001000018694 so I can do everything.  What do you mean you can't create Tenants for the buyers?  I thought you were administrator on OTC?

**Comment by eeckstei** [comment]
@mebster : After Deployment of a Tenant further accounts must be created by a Tenant Admin due to Security Reasons. A Tenant Admin is a named person which user is created during the creation of an Tenant. Tenant Admin for the upcoming BG Tenants is a BG responsible. Only this guy can decide who are allowed to access and manage his tenant.

**Comment by mebster** [comment]
@eeckstei ok then, please create new tenants for the buyers using the email addresses Lionel provided you.

**Comment by eeckstei** [comment]
@mebster : OK, sent an eMail to Jurry to request this in this way.

**Comment by eeckstei** [comment]
@mebster: Had a call with Jurry. BG must be Tenant Admin and this will be not changed. Please clarify this topic in todays call with Jurry and RHEA Group at 17:00!

**Comment by cgizzi** [comment]
The strategy reported by MEB/Lionel has been agreed by BG and OTC. So this specific issue is closed.
