### ISSUE TITLE
Create EMBL-EBI Benchmarking Suite component in SS

### ISSUE THREAD

**Issue by cjdcordeiro** [SixSq/hn-prototype-platform#29]
This requires input from someone in EMBL-EBI as authentication is needed for benchmarking networking through GridFTP - https://github.com/EMBL-EBI-TSI/cloud-benchmarks

**Comment by elegoff** [comment]
Current status : 
- Deployed a Centos 7 image (https://nuv.la/module/examples/images/centos-7/11611) on ExoScale with Small flavor
- This does not comply with EMBL requirements where 20GB disk space should be available
Also need to make sure the ssh keypair has read permission for the user running the benchmarks
- Will reuse a bigger image flavor like  https://nuv.la/module/cristovao/random/centos-7-mediumFlavor

**Comment by retrack** [comment]
Deploying a Small instance with a 20GB from the go is possible. Look at the "rootdisksize" in the deployVirtualMachine API command.

You can also deploy a default Small with 10GB and then scale to 20GB.

**Comment by elegoff** [comment]
- ssh connection is apparently possible only after the .ssh/config file is created by the cloud_testing.sh script, 
any attempts before that phase will generate a permission denied error
- copy/pasting the private key (id_rsa) via component input parameter is currently replacing line breaks with spaces, and the key is no more usable
- tried to reconstitute the private key with script (replacing back spaces with linebreaks) but no success so far (mainly because -----BEGIN RSA PRIVATE KEY----- and -----END RSA PRIVATE KEY----- have to contain spaces...)

**Comment by elegoff** [comment]
Latest version of the component recipe is successful allows automatic launch of the EMBL benchmark script
The latest issues we had were mainly because the user who launches the script has to be non root but has to belong to sudoers and requires non interactive password prompt.
Also note that the SSH private has to be be provided as a base64 encoded runtime parameter
(for both security reasons and to avoid line breaks issues mentioned in previous comment
Closing the issue

**Comment by elegoff** [comment]
After a long running time, the script eventually failed with
`dd: memory exhausted by input buffer of size 1073741824 bytes (1.0 GiB) `
Reopening

**Comment by elegoff** [comment]
The memory issue is fixed after upgrading  exoscale instance type from Micro to Medium
Closing
